// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9OSXEKb20CHzlS7wIedxKHIL6fd9WfVs',
    appId: '1:168165339416:web:44f3cad1f90a33e7caee6d',
    messagingSenderId: '168165339416',
    projectId: 'smart-blood-donation-364313',
    authDomain: 'smart-blood-donation-364313.firebaseapp.com',
    storageBucket: 'smart-blood-donation-364313.appspot.com',
    measurementId: 'G-P533P03RWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzUKX7CWfqIyFh3CMzVp_eEwHwiP2ufuE',
    appId: '1:168165339416:android:58d7ef92c33bd785caee6d',
    messagingSenderId: '168165339416',
    projectId: 'smart-blood-donation-364313',
    storageBucket: 'smart-blood-donation-364313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs5sg6diCeZxJkMFoAj_6VgN08rEMueDk',
    appId: '1:168165339416:ios:dd89bf070aea11e1caee6d',
    messagingSenderId: '168165339416',
    projectId: 'smart-blood-donation-364313',
    storageBucket: 'smart-blood-donation-364313.appspot.com',
    iosClientId: '168165339416-d701fj0b7vvfkicp203ah5s6bcldbpkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartblood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs5sg6diCeZxJkMFoAj_6VgN08rEMueDk',
    appId: '1:168165339416:ios:dd89bf070aea11e1caee6d',
    messagingSenderId: '168165339416',
    projectId: 'smart-blood-donation-364313',
    storageBucket: 'smart-blood-donation-364313.appspot.com',
    iosClientId: '168165339416-d701fj0b7vvfkicp203ah5s6bcldbpkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartblood',
  );
}
